# --- Datasource ---
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=orders
%dev.quarkus.datasource.password=orders
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orders

# --- Hibernate + Flyway (el schema lo manejará Flyway, no Hibernate) ---
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true

# --- Tests: PostgreSQL efímero vía Dev Services (imagen ya presente en local) ---
quarkus.datasource.devservices.image-name=postgres:16-alpine
