create table product (
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    sku      varchar(64)  not null,
    quantity integer      not null,
    constraint uq_product_sku unique (sku)
);
