-- Historial de movimientos de stock (github-24). Sin cascade: el producto nunca se borra
-- físicamente (borrado lógico, V2), así que su historial permanece.
create table stock_movement (
    id                 bigint  generated by default as identity primary key,
    product_id         bigint  not null references product (id),
    delta              integer not null,
    previous_quantity  integer not null,
    resulting_quantity integer not null,
    occurred_at        timestamp with time zone not null
);

create index ix_stock_movement_product_occurred
    on stock_movement (product_id, occurred_at desc, id desc);
